/**
 * Compiles one extension's own stylesheet.
 *
 * An extension writes `gap-1.5` and `bg-panel` exactly as the shell does, and
 * for a long time neither worked. The reason is worth stating because it is
 * invisible: Tailwind generates only the classes it *finds in source files*,
 * the window's build scans the window's own `src`, and an extension is not in
 * it. Every utility an extension used that the shell did not happen to use as
 * well silently produced no rule at all — a layout that reads as a redesign
 * and is really an empty stylesheet.
 *
 * So a package carries its own rules, and this is where they are made. What it
 * does **not** carry is any value: the entry imports the theme the contract
 * publishes, which is declared `@theme inline`, so `bg-panel` compiles to
 * `background-color: var(--surface-panel)` and the window supplies the colour
 * at paint. Retinting the window retints every extension in it, with nothing
 * rebuilt.
 *
 * That is the whole of the division, and it is the same one the module build
 * makes for different reasons:
 *
 * - **One copy** of anything with identity or with a design in it — React, the
 *   component library, the tokens. Two would be two behaviours, or two designs
 *   drifting apart.
 * - **Its own copy** of anything that is a pure rule — an icon, a utility
 *   class. `.gap-1\.5` means the same thing wherever it is compiled, so two
 *   packages carrying it cost forty identical bytes each and can never
 *   disagree.
 *
 * The author owns the entry. If `src/index.css` exists it is used as written,
 * so anything CSS can express — a component the shell has no equivalent for, a
 * keyframe, a media query — belongs there beside the imports. When there is no
 * such file the default below is used, which is the same thing with nothing
 * added.
 */

import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const require = createRequire(import.meta.url);

/** Where an author's own stylesheet goes, when they want one. */
export const ENTRY = "src/index.css";

/**
 * The entry used for a package that has not written one.
 *
 * `utilities.css` alone rather than `tailwindcss`, which would also bring
 * preflight — a second reset in a document that already has one, restyling the
 * window around the extension rather than the extension.
 */
function defaultEntry() {
  return [
    "/* Generated by sync-ext. Write src/index.css to take this over. */",
    '@import "@sync-buzz/extension-api/extension.css";',
    '@source "./";',
    "",
  ].join("\n");
}

function cli() {
  // Resolved from this package rather than found on the path: an extension
  // repository depends on the contract, not on Tailwind, and asking it to
  // install a second copy would be asking it to keep two versions in step.
  //
  // Through `package.json` and then the `bin` entry, because the CLI exports
  // nothing but its own manifest — the executable is not a subpath anybody may
  // import, and guessing at `dist/` would break on the release that moves it.
  const manifest = require.resolve("@tailwindcss/cli/package.json");
  const bin = require(manifest).bin;
  const entry = typeof bin === "string" ? bin : bin.tailwindcss;
  return join(dirname(manifest), entry);
}

/**
 * @param folder The extension's own directory.
 * @param output Where the stylesheet goes, relative to `folder`.
 * @returns The path written, or `null` when the package ships no module.
 */
export async function styles(folder, output, { watch = false, minify = true } = {}) {
  const written = join(folder, output);
  mkdirSync(dirname(written), { recursive: true });

  const authored = join(folder, ENTRY);
  const temporary = join(folder, ".sync-ext-entry.css");
  const entry = existsSync(authored) ? authored : temporary;
  if (entry === temporary) writeFileSync(temporary, defaultEntry());

  const argv = ["--input", entry, "--output", written];
  if (minify && !watch) argv.push("--minify");
  if (watch) argv.push("--watch");

  try {
    await new Promise((settle, refuse) => {
      const run = spawn(process.execPath, [cli(), ...argv], {
        cwd: folder,
        stdio: ["ignore", "ignore", "inherit"],
      });
      run.on("error", refuse);
      run.on("exit", (code) =>
        code === 0
          ? settle()
          : refuse(new Error(`Tailwind refused ${relative(folder, entry)} (exit ${code}).`)),
      );
    });
  } finally {
    if (entry === temporary && !watch) rmSync(temporary, { force: true });
  }

  return written;
}
